import type { Metadata } from "next";

export const revalidate = 86400;
const siteUrl = process.env.NEXT_PUBLIC_APP_URL || "https://pixelliftai.online";

export const metadata: Metadata = {
  title: "Disclaimer - PixelLift AI",
  description: "Disclaimer for PixelLift AI.",
};

const sections = [
  {
    title: "1. General Information Disclaimer",
    body: [
      "PixelLift AI is provided as an AI-powered image enhancement and educational content platform.",
      "All content and tools on PixelLift AI are for general informational, educational, and practical use only. Nothing on PixelLift AI should be considered legal, financial, professional, or technical advice for your specific situation.",
    ],
  },
  {
    title: "2. AI Output Disclaimer",
    bullets: [
      "Every image will be enhanced successfully.",
      "The result will match your expectations.",
      "The enhanced image will be error-free.",
      "Faces, objects, text, or details will remain perfectly accurate.",
      "The output will be suitable for professional, commercial, legal, official, or sensitive use.",
    ],
  },
  {
    title: "3. Image Ownership Disclaimer",
    body: [
      "You retain ownership of the images you upload to PixelLift AI. However, by uploading an image, you confirm that you own the image or have the legal right, license, consent, or permission to upload and process it.",
    ],
  },
  {
    title: "4. No Professional Editing Guarantee",
    body: [
      "PixelLift AI is not a replacement for professional photography, retouching, restoration, forensic image analysis, or expert design work. While the service may improve image quality, it cannot guarantee professional-grade results in every case.",
    ],
  },
  {
    title: "5. Temporary Availability Disclaimer",
    body: [
      "PixelLift AI may provide enhanced image results through temporary links generated by third-party processing services. These links may expire, become unavailable, or fail to load after a period of time.",
    ],
  },
  {
    title: "6. Third-Party Services Disclaimer",
    bullets: [
      "Vercel",
      "Supabase",
      "Picsart",
      "Google OAuth",
      "Google AdSense",
      "Other infrastructure or analytics providers",
    ],
  },
  {
    title: "7. Blog and Educational Content Disclaimer",
    body: [
      "PixelLift AI may publish blog posts, tutorials, guides, reviews, comparisons, and educational content related to AI tools, image enhancement, photo editing, and digital technology. This content is provided for general educational and informational purposes only.",
    ],
  },
  {
    title: "8. Advertising Disclaimer",
    body: [
      "PixelLift AI may display advertisements on blog pages through third-party advertising networks such as Google AdSense. Your interaction with any advertisement, advertiser, product, service, or external website is solely between you and the relevant third party.",
    ],
  },
  {
    title: "9. External Links Disclaimer",
    body: [
      "PixelLift AI may contain links to third-party websites, tools, platforms, resources, or services. These links are provided for convenience and informational purposes only.",
    ],
  },
  {
    title: "10. Service Availability Disclaimer",
    body: [
      "PixelLift AI is provided on an as is and as available basis. We do not guarantee that the service will always be available, uninterrupted, secure, fast, or error-free.",
    ],
  },
  {
    title: "11. Security Disclaimer",
    body: [
      "We use reasonable security practices to protect PixelLift AI and user data. However, no online platform, AI service, database, hosting provider, or transmission method is completely secure.",
    ],
  },
  {
    title: "12. Limitation of Responsibility",
    body: [
      "To the maximum extent permitted by law, PixelLift AI and its owners, developers, employees, contractors, partners, and service providers are not responsible for any loss, damage, claim, liability, or issue arising from your use of the service or third-party service failures.",
    ],
  },
  {
    title: "13. User Responsibility",
    bullets: [
      "The images you upload.",
      "The rights and permissions for uploaded content.",
      "Reviewing enhanced image outputs.",
      "Downloading results promptly.",
      "Complying with applicable laws.",
      "Protecting your account credentials.",
      "Using the service responsibly.",
    ],
  },
  {
    title: "14. Changes to This Disclaimer",
    body: [
      "We may update this Disclaimer from time to time. When we update it, we will revise the Last Updated date above.",
    ],
  },
  {
    title: "15. Contact Us",
    body: [
      "PixelLift AI",
      "Operator: PixelLift AI",
      "Address: Not publicly listed.",
      "Jurisdiction: Not publicly specified.",
      "Contact: Use the Contact page on the website.",
      `Website: ${siteUrl}`,
    ],
  },
];

export default function DisclaimerPage() {
  return (
    <div className="relative overflow-hidden bg-[#F8FAFC]">
      <div className="pointer-events-none absolute inset-x-0 top-0 h-80 bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.08),transparent_42%)]" />
      <div className="relative mx-auto max-w-4xl px-4 py-12 sm:px-6 sm:py-16 lg:px-8 lg:py-20">
        <header className="max-w-3xl">
          <p className="text-sm font-semibold uppercase tracking-[0.25em] text-blue-600">Disclaimer</p>
          <h1 className="mt-4 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl lg:text-5xl">
            Disclaimer for PixelLift AI
          </h1>
          <p className="mt-5 text-base leading-7 text-slate-600 sm:text-lg sm:leading-8">
            This Disclaimer applies to your use of PixelLift AI, including the website, AI image enhancement tool,
            user dashboard, blog, and related services.
          </p>
          <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-[0_20px_60px_rgba(15,23,42,0.06)]">
            <p className="text-sm text-slate-500">Effective Date: May 18, 2026</p>
            <p className="mt-1 text-sm text-slate-500">Last Updated: May 18, 2026</p>
          </div>
        </header>

        <div className="mt-12 space-y-6">
          {sections.map((section) => (
            <section
              key={section.title}
              className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-[0_20px_60px_rgba(15,23,42,0.06)] sm:p-8"
            >
              <h2 className="text-xl font-semibold text-slate-900 sm:text-2xl">{section.title}</h2>
              <div className="mt-4 space-y-4 text-sm leading-7 text-slate-600">
                {section.body?.map((line) => <p key={line}>{line}</p>)}
                {section.bullets ? (
                  <ul className="list-disc space-y-2 pl-5">
                    {section.bullets.map((item) => (
                      <li key={item}>{item}</li>
                    ))}
                  </ul>
                ) : null}
              </div>
            </section>
          ))}
        </div>
      </div>
    </div>
  );
}
